spring:
  datasource:
    #url: jdbc:h2:tcp://localhost/~/jpashop
    url: jdbc:mysql://127.0.0.1:3306/mydb
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100              # Lazy로딩되는 엔티티를 in쿼리를 통해 한번에 가져옴 (in쿼리의 파라미터 수)
                                                   # 엔티티 단위로 적용시 @BatchSize(size=N)


logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
